version: '3'

services:

  postgres:
    image: postgres:15.4-alpine
    container_name: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: crm
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    networks:
      - net_3

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - net_3

volumes:
  postgres-volume:
    driver: local

networks:
  net_3:
    driver: bridge
